{
  "openapi": "3.0.1",
  "info": {
    "title": "APIs.guru",
    "description": "Wikipedia for Web APIs. Repository of API specs in OpenAPI 3.0 format.\n\n**Warning**: If you want to be notified about changes in advance please join our [Slack channel](https://join.slack.com/t/mermade/shared_invite/zt-g78g7xir-MLE_CTCcXCdfJfG3CJe9qA).\n\nClient sample: [[Demo]](https://apis.guru/simple-ui) [[Repo]](https://github.com/APIs-guru/simple-ui)\n",
    "contact": {
      "name": "APIs.guru",
      "url": "https://APIs.guru",
      "email": "mike.ralphson@gmail.com"
    },
    "license": {
      "name": "CC0 1.0",
      "url": "https://github.com/APIs-guru/openapi-directory#licenses"
    },
    "version": "2.0.2",
    "x-apisguru-categories": [
      "open_data",
      "developer_tools"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_apis.guru_branding_logo_vertical.svg"
    },
    "x-origin": [
      {
        "format": "swagger",
        "url": "https://api.apis.guru/v2/swagger.json",
        "version": "2.0"
      }
    ],
    "x-providerName": "apis.guru",
    "x-tags": [
      "API",
      "Catalog",
      "Directory",
      "REST",
      "Swagger",
      "OpenAPI"
    ]
  },
  "externalDocs": {
    "url": "https://github.com/APIs-guru/openapi-directory/blob/master/API.md"
  },
  "servers": [
    {
      "url": "https://api.apis.guru/v2/"
    }
  ],
  "tags": [
    {
      "name": "APIs",
      "description": "Actions relating to APIs in the collection"
    }
  ],
  "paths": {
    "/list.json": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "List all APIs",
        "description": "List all APIs in the directory.\nReturns links to OpenAPI specification for each API in the directory.\nIf API exist in multiple versions `preferred` one is explicitly marked.\n\nSome basic info from OpenAPI spec is cached inside each object.\nThis allows to generate some simple views without need to fetch OpenAPI spec for each API.\n",
        "operationId": "listAPIs",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json; charset\u003dutf-8": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "$ref": "#/components/schemas/API"
                  },
                  "description": "List of API details.\nIt is a JSON object with API IDs(`\u003cprovider\u003e[:\u003cservice\u003e]`) as keys.\n",
                  "example": {
                    "googleapis.com:drive": {
                      "added": "2015-02-22T20:00:45.000Z",
                      "preferred": "v3",
                      "versions": {
                        "v2": {
                          "added": "2015-02-22T20:00:45.000Z",
                          "info": {
                            "title": "Drive",
                            "version": "v2",
                            "x-apiClientRegistration": {
                              "url": "https://console.developers.google.com"
                            },
                            "x-logo": {
                              "url": "https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png"
                            },
                            "x-origin": {
                              "format": "google",
                              "url": "https://www.googleapis.com/discovery/v1/apis/drive/v2/rest",
                              "version": "v1"
                            },
                            "x-preferred": false,
                            "x-providerName": "googleapis.com",
                            "x-serviceName": "drive"
                          },
                          "swaggerUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.json",
                          "swaggerYamlUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.yaml",
                          "updated": "2016-06-17T00:21:44.000Z"
                        },
                        "v3": {
                          "added": "2015-12-12T00:25:13.000Z",
                          "info": {
                            "title": "Drive",
                            "version": "v3",
                            "x-apiClientRegistration": {
                              "url": "https://console.developers.google.com"
                            },
                            "x-logo": {
                              "url": "https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png"
                            },
                            "x-origin": {
                              "format": "google",
                              "url": "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
                              "version": "v1"
                            },
                            "x-preferred": true,
                            "x-providerName": "googleapis.com",
                            "x-serviceName": "drive"
                          },
                          "swaggerUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.json",
                          "swaggerYamlUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.yaml",
                          "updated": "2016-06-17T00:21:44.000Z"
                        }
                      }
                    }
                  },
                  "x-schemaName": "APIs"
                }
              },
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "$ref": "#/components/schemas/API"
                  },
                  "description": "List of API details.\nIt is a JSON object with API IDs(`\u003cprovider\u003e[:\u003cservice\u003e]`) as keys.\n",
                  "example": {
                    "googleapis.com:drive": {
                      "added": "2015-02-22T20:00:45.000Z",
                      "preferred": "v3",
                      "versions": {
                        "v2": {
                          "added": "2015-02-22T20:00:45.000Z",
                          "info": {
                            "title": "Drive",
                            "version": "v2",
                            "x-apiClientRegistration": {
                              "url": "https://console.developers.google.com"
                            },
                            "x-logo": {
                              "url": "https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png"
                            },
                            "x-origin": {
                              "format": "google",
                              "url": "https://www.googleapis.com/discovery/v1/apis/drive/v2/rest",
                              "version": "v1"
                            },
                            "x-preferred": false,
                            "x-providerName": "googleapis.com",
                            "x-serviceName": "drive"
                          },
                          "swaggerUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.json",
                          "swaggerYamlUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.yaml",
                          "updated": "2016-06-17T00:21:44.000Z"
                        },
                        "v3": {
                          "added": "2015-12-12T00:25:13.000Z",
                          "info": {
                            "title": "Drive",
                            "version": "v3",
                            "x-apiClientRegistration": {
                              "url": "https://console.developers.google.com"
                            },
                            "x-logo": {
                              "url": "https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png"
                            },
                            "x-origin": {
                              "format": "google",
                              "url": "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
                              "version": "v1"
                            },
                            "x-preferred": true,
                            "x-providerName": "googleapis.com",
                            "x-serviceName": "drive"
                          },
                          "swaggerUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.json",
                          "swaggerYamlUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.yaml",
                          "updated": "2016-06-17T00:21:44.000Z"
                        }
                      }
                    }
                  },
                  "x-schemaName": "APIs",
                  "required": true,
                  "in": "response_body"
                }
              }
            }
          }
        }
      }
    },
    "/metrics.json": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "Get basic metrics",
        "description": "Some basic metrics for the entire directory.\nJust stunning numbers to put on a front page and are intended purely for WoW effect :)\n",
        "operationId": "getMetrics",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json; charset\u003dutf-8": {
                "schema": {
                  "required": [
                    "numAPIs",
                    "numEndpoints",
                    "numSpecs"
                  ],
                  "type": "object",
                  "properties": {
                    "numAPIs": {
                      "minimum": 1.0,
                      "type": "integer",
                      "description": "Number of APIs"
                    },
                    "numEndpoints": {
                      "minimum": 1.0,
                      "type": "integer",
                      "description": "Total number of endpoints inside all specifications"
                    },
                    "numSpecs": {
                      "minimum": 1.0,
                      "type": "integer",
                      "description": "Number of API specifications including different versions of the same API"
                    }
                  },
                  "description": "List of basic metrics",
                  "example": {
                    "numAPIs": 238.0,
                    "numEndpoints": 6448.0,
                    "numSpecs": 302.0
                  },
                  "x-schemaName": "Metrics"
                }
              },
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "numAPIs": {
                      "minimum": 1.0,
                      "type": "integer",
                      "description": "Number of APIs",
                      "required": true,
                      "in": "RESPONSE_BODY"
                    },
                    "numEndpoints": {
                      "minimum": 1.0,
                      "type": "integer",
                      "description": "Total number of endpoints inside all specifications",
                      "required": true,
                      "in": "RESPONSE_BODY"
                    },
                    "numSpecs": {
                      "minimum": 1.0,
                      "type": "integer",
                      "description": "Number of API specifications including different versions of the same API",
                      "required": true,
                      "in": "RESPONSE_BODY"
                    }
                  },
                  "description": "List of basic metrics",
                  "example": {
                    "numAPIs": 238.0,
                    "numEndpoints": 6448.0,
                    "numSpecs": 302.0
                  },
                  "x-schemaName": "Metrics",
                  "required": true,
                  "in": "response_body"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "API": {
        "required": [
          "added",
          "preferred",
          "versions"
        ],
        "type": "object",
        "properties": {
          "added": {
            "type": "string",
            "description": "Timestamp when the API was first added to the directory",
            "format": "date-time"
          },
          "preferred": {
            "type": "string",
            "description": "Recommended version"
          },
          "versions": {
            "minProperties": 1.0,
            "type": "object",
            "additionalProperties": {
              "$ref": "#/components/schemas/ApiVersion"
            },
            "description": "List of supported versions of the API"
          }
        },
        "description": "Meta information about API",
        "x-schemaName": "API"
      },
      "APIs": {
        "type": "object",
        "additionalProperties": {
          "$ref": "#/components/schemas/API"
        },
        "description": "List of API details.\nIt is a JSON object with API IDs(`\u003cprovider\u003e[:\u003cservice\u003e]`) as keys.\n",
        "example": {
          "googleapis.com:drive": {
            "added": "2015-02-22T20:00:45.000Z",
            "preferred": "v3",
            "versions": {
              "v2": {
                "added": "2015-02-22T20:00:45.000Z",
                "info": {
                  "title": "Drive",
                  "version": "v2",
                  "x-apiClientRegistration": {
                    "url": "https://console.developers.google.com"
                  },
                  "x-logo": {
                    "url": "https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png"
                  },
                  "x-origin": {
                    "format": "google",
                    "url": "https://www.googleapis.com/discovery/v1/apis/drive/v2/rest",
                    "version": "v1"
                  },
                  "x-preferred": false,
                  "x-providerName": "googleapis.com",
                  "x-serviceName": "drive"
                },
                "swaggerUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.json",
                "swaggerYamlUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.yaml",
                "updated": "2016-06-17T00:21:44.000Z"
              },
              "v3": {
                "added": "2015-12-12T00:25:13.000Z",
                "info": {
                  "title": "Drive",
                  "version": "v3",
                  "x-apiClientRegistration": {
                    "url": "https://console.developers.google.com"
                  },
                  "x-logo": {
                    "url": "https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png"
                  },
                  "x-origin": {
                    "format": "google",
                    "url": "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
                    "version": "v1"
                  },
                  "x-preferred": true,
                  "x-providerName": "googleapis.com",
                  "x-serviceName": "drive"
                },
                "swaggerUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.json",
                "swaggerYamlUrl": "https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.yaml",
                "updated": "2016-06-17T00:21:44.000Z"
              }
            }
          }
        },
        "x-schemaName": "APIs"
      },
      "ApiVersion": {
        "required": [
          "added",
          "info",
          "swaggerUrl",
          "swaggerYamlUrl",
          "updated"
        ],
        "type": "object",
        "properties": {
          "added": {
            "type": "string",
            "description": "Timestamp when the version was added",
            "format": "date-time"
          },
          "externalDocs": {
            "type": "object",
            "properties": {},
            "description": "Copy of `externalDocs` section from OpenAPI definition"
          },
          "info": {
            "type": "object",
            "properties": {},
            "description": "Copy of `info` section from OpenAPI definition"
          },
          "swaggerUrl": {
            "type": "string",
            "description": "URL to OpenAPI definition in JSON format",
            "format": "url"
          },
          "swaggerYamlUrl": {
            "type": "string",
            "description": "URL to OpenAPI definition in YAML format",
            "format": "url"
          },
          "updated": {
            "type": "string",
            "description": "Timestamp when the version was updated",
            "format": "date-time"
          }
        },
        "x-schemaName": "ApiVersion"
      },
      "Metrics": {
        "required": [
          "numAPIs",
          "numEndpoints",
          "numSpecs"
        ],
        "type": "object",
        "properties": {
          "numAPIs": {
            "minimum": 1.0,
            "type": "integer",
            "description": "Number of APIs"
          },
          "numEndpoints": {
            "minimum": 1.0,
            "type": "integer",
            "description": "Total number of endpoints inside all specifications"
          },
          "numSpecs": {
            "minimum": 1.0,
            "type": "integer",
            "description": "Number of API specifications including different versions of the same API"
          }
        },
        "description": "List of basic metrics",
        "example": {
          "numAPIs": 238.0,
          "numEndpoints": 6448.0,
          "numSpecs": 302.0
        },
        "x-schemaName": "Metrics"
      }
    }
  }
}